apiVersion: skaffold/v4beta1
king: Config
metadata:
  name: skaffold
build:
  artifacts:
  - image: luciano/comments:1.0.0
    context: comments
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: '*.js'
          dest: .
manifests:
  rawYaml:
  - ./infra/k8s/*